import Foundation

struct TodoItem: Identifiable, Codable, Hashable {
    var id: String = UUID().uuidString
    var text: String
    var isCompleted: Bool = false
    var status: TodoStatus? // Optional for backward compatibility
    var createdAt: Date = Date()
    var dueDate: Date?
    var isAutoGenerated: Bool? // Optional to prevent Codable decoding errors for existing data
    
    // New Feature Properties
    var priority: TodoPriority?
    var assignee: String?
    var subTasks: [TodoItem]?
    var tags: [String]?
    
    var currentStatus: TodoStatus {
        if let status = status { return status }
        return isCompleted ? .done : .todo
    }
}
